package server.command;

public enum CommandType {
    REGISTER, LOGIN, DEPOSIT_MONEY, LIST_OFFERINGS, BUY, SELL, GET_WALLET_SUMMARY, GET_WALLET_OVERALL_SUMMARY, WHO_AM_I, DISCONNECT, UNKNOWN_COMMAND;
}
